Repository resilient-tech/india-compliance, pull requests merged in 2022-10, with the labels that each got.

#273 ci: mergify for backport of pull requests
  .github/workflows/backport.yml
Labels: backport version-14-hotfix

#276 ci: workflow for backport of PRs
  .github/workflows/backport.yml
Labels: backport version-14-hotfix

#277 ci: fix token expected for backport workflow
  .github/workflows/backport.yml
Labels: backport version-14-hotfix

#278 ci: add bot token for backport
  .github/workflows/backport.yml
Labels: backport version-14-hotfix

#272 ci: install respective branch
  .github/helper/install.sh
  .github/workflows/server-tests.yml
Labels: backport version-14-hotfix

#285 ci: specify correct branch for push events
  .github/helper/install.sh
  .github/workflows/server-tests.yml
Labels: squash, backport version-14-hotfix

#292 chore: workflow for semantic release
  .github/workflows/on_release.yml
  .releaserc
Labels: backport version-14-hotfix

#302 fix: support for vue3
  india_compliance/public/js/india_compliance_account/IndiaComplianceAccountApp.vue
  india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
  india_compliance/public/js/india_compliance_account/pages/AuthPage.vue
  india_compliance/public/js/india_compliance_account/pages/MailSentPage.vue
  india_compliance/public/js/india_compliance_account/pages/PaymentPage.vue
  india_compliance/public/js/india_compliance_account/pages/PurchaseCreditsPage.vue
  india_compliance/public/js/india_compliance_account/router.js
  india_compliance/public/js/india_compliance_account/store/index.js
Labels: wip

#307 fix: remove `ecommerce_gstin` from Purchase Invoice and related reports
  india_compliance/gst_india/report/gst_itemised_purchase_register/gst_itemised_purchase_register.py
  india_compliance/gst_india/report/gst_purchase_register/gst_purchase_register.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/remove_old_fields.py
  india_compliance/patches/v14/remove_ecommerce_gstin_from_purchase_invoice.py
Labels: backport version-14-hotfix

#310 fix: set page title when routing to page
  india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js
Labels: backport version-14-hotfix
