Repository resilient-tech/india-compliance, pull requests merged in 2023-04, with the labels that each got.

#544 fix: e-way bill print breaking into two pages with irn
  india_compliance/gst_india/print_format/e_waybill/e_waybill.css
Labels: backport version-14-hotfix

#548 fix: update state name to `Puducherry`
  india_compliance/gst_india/constants/__init__.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_state_name_to_puducherry.py
  india_compliance/public/js/india_compliance_account/pages/PaymentPage.vue
Labels: backport version-14-hotfix

#516 fix: rename `Import of Capital Goods` to `Import of Goods`
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/rename_import_of_capital_goods.py
  india_compliance/patches/post_install/set_gst_category.py
Labels: squash

#556 fix: use `doc_events` to set item taxes
  india_compliance/gst_india/overrides/item.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix

#558 fix: reset `fetch_from` in Place of Supply fields
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix

#563 fix: allow common enrolment number to be used as Transporter ID
  india_compliance/gst_india/overrides/supplier.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/tests/test_records.json
Labels: backport version-14-hotfix

#571 fix: error creating company fixtures if fiscal year is not found
  india_compliance/income_tax_india/overrides/company.py
Labels: backport version-14-hotfix

#570 fix: misc UX fixes for audit trail
  india_compliance/audit_trail/client_scripts/accounts_settings.js
  india_compliance/audit_trail/constants/custom_fields.py
  india_compliance/patches.txt
  india_compliance/public/js/audit_trail_notification.js
  india_compliance/public/js/setup_wizard.js
Labels: backport version-14-hotfix

#568 fix: dont validate transaction if mandatory fields are ignored during save
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#576 fix: use `base_rounding_adjustment` instead of `rounding_adjustment`
  india_compliance/gst_india/utils/transaction_data.py
Labels: squash, backport version-14-hotfix

#578 refactor: consistent naming for amount keys in `transaction_details`
  india_compliance/gst_india/overrides/test_transaction_data.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: squash, backport version-14-hotfix

#583 fix: better fallback for `doc.customer_name`
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix

#532 refactor: get_depreciation_amount according to frappe/erpnext#34646 [develop] (#532
  india_compliance/hooks.py
  india_compliance/income_tax_india/overrides/asset_depreciation_schedule.py
Labels: do not backport

#587 fix: set discount amount if cash discount is checked
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: backport version-14-hotfix

#603 fix: add validation for place of supply format
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#600 fix: correct b2cs and b2cl report and its credit notes
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix

#615 fix: transporter_name
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix

#627 fix: dont rely on field options when validating place of supply
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix

#630 fix: improved setter and validation for `gst_transporter_id`
  india_compliance/gst_india/client_scripts/supplier.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/supplier.py
  india_compliance/patches.txt
Labels: squash, backport version-14-hotfix

#459 fix: error handling for manually cancelled e-waybill or e-Invoice
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/api_classes/e_waybill.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
Labels: squash, backport version-14-hotfix

#642 fix: prefer legal name over address title for buyer and seller details
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/overrides/test_transaction_data.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: backport version-14-hotfix
