Repository resilient-tech/india-compliance, pull requests merged in 2023-07, with the labels that each got.

#818 fix: standardize report override for sales/purchase reports
  india_compliance/gst_india/report/gst_itemised_purchase_register/gst_itemised_purchase_register.py
  india_compliance/gst_india/report/gst_itemised_sales_register/gst_itemised_sales_register.py
  india_compliance/gst_india/report/gst_purchase_register/gst_purchase_register.py
  india_compliance/gst_india/report/gst_sales_register/gst_sales_register.py
Labels: backport version-14-hotfix

#832 chore: remove GSTIN doctype for now
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/patches.txt
Labels: backport version-14-hotfix

#834 fix: provision to update gst category using API
  india_compliance/gst_india/doctype/gst_settings/gst_settings.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/patches/post_install/update_gstin_and_gst_category.py
Labels: squash, backport version-14-hotfix

#847 feat: GSTR3b detailed breackup report
  india_compliance/gst_india/report/gstr_3b_details/__init__.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.js
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.json
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
Labels: backport version-14-hotfix

#844 fix: update taxable value for non-gst_items
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix

#824 fix: improve error message for validating country codes
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix

#836 feat: reverse charge in purchase document
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/supplier.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/set_reverse_charge_applicability_in_supplier.py
  india_compliance/public/js/transaction.js
Labels: backport version-14-hotfix

#800 fix: set e-invoice status as Failed on exception
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix

#856 fix: display condition for reverse charge applicabilty field in supplier
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
Labels: squash, backport version-14-hotfix

#862 fix: corrected gstr1 json format for nil-rated/exempted
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix

#863 fix: skip non-gst invoices in b2b gstr1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix

#789 fix: tds adjusted totals for e-Invoice and e-Waybill
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/hooks.py
  india_compliance/income_tax_india/overrides/tax_withholding_category.py
Labels: squash, backport version-14-hotfix

#869 fix: update taxable values for non-gst items
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#858 fix: update creds for sandbox mode
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix

#336 fix: Vue3 Router Issues
  india_compliance/gst_india/page/india_compliance_account/india_compliance_account.js
  india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
  india_compliance/public/js/india_compliance_account/pages/PaymentPage.vue
  india_compliance/public/js/india_compliance_account/pages/PurchaseCreditsPage.vue
  india_compliance/public/js/india_compliance_account/router.js
  india_compliance/public/js/india_compliance_account/store/modules/account.js
Labels: do not backport

#859 fix: patch to check version compatibility for dependencies on other apps
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/check_version_compatibility.py
  india_compliance/patches/v15/check_version_compatibility.py
Labels: backport version-14-hotfix

#798 feat: Fetch e-Waybills by date
  india_compliance/gst_india/api_classes/e_waybill.py
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/utils/e_waybill.py
Labels: squash, backport version-14-hotfix

#876 fix: create gstin field in expense claim doctype hrms
  india_compliance/gst_india/client_scripts/expense_claim.js
  india_compliance/gst_india/client_scripts/journal_entry.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/uninstall.py
  india_compliance/hooks.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/check_version_compatibility.py
  india_compliance/uninstall.py
Labels: squash, backport version-14-hotfix

#888 fix: improve version patch
  india_compliance/__init__.py
  india_compliance/hooks.py
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix

#894 fix: improve version check patch
  india_compliance/__init__.py
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix

#892 fix: show message if gst applicable but not applied in sales invoice
  india_compliance/gst_india/client_scripts/sales_invoice.js
Labels: backport version-14-hotfix

#885 fix: inform user if the e-invoice or e-way bill was created in sandbox mode
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/doctype/e_invoice_log/e_invoice_log.json
  india_compliance/gst_india/doctype/e_waybill_log/e_waybill_log.json
  india_compliance/gst_india/overrides/delivery_note.py
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
Labels: squash, p1, backport version-14-hotfix

#902 fix: property_setter validation and patch message condition
  india_compliance/gst_india/setup/__init__.py
  india_compliance/patches/post_install/update_gstin_and_gst_category.py
Labels: backport version-14-hotfix

#906 ci: set `db_type` as mariadb in `site_config.json`
  .github/helper/site_config.json
Labels: backport version-14-hotfix

#908 fix: improve implementation for sandbox desc
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
Labels: backport version-14-hotfix

#912 fix: update place of supply for sandbox mode
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix

#911 fix: unassigned variables in gstr3b details report
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
Labels: backport version-14-hotfix
