Repository resilient-tech/india-compliance, pull requests merged in 2023-12, with the labels that each got.

#1369 test: account for changes made in ERPNext payment entry creation
  india_compliance/gst_india/overrides/test_advance_payment_entry.py
Labels: backport version-15-hotfix

#1401 fix: status for suspended GSTINs
  india_compliance/gst_india/doctype/gstin/gstin.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1402 fix: extra whitespace in label
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix, backport version-15-hotfix

#1397 fix(ux): Dashboard Links for BOE
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#1410 ci: update docs requirement for other branches
  .github/helper/documentation.py
Labels: backport version-14-hotfix

#1399 fix: patch to update vehicle no in Purchase Receipt
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_vehicle_no_field_in_purchase_receipt.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1423 fix: handle GSPGSTDOWN error
  india_compliance/exceptions.py
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1409 fix: dynamic tax rate for default tax template in setup wizard
  india_compliance/gst_india/client_scripts/company.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/company.py
  india_compliance/gst_india/overrides/test_company.py
  india_compliance/patches.txt
  india_compliance/public/js/setup_wizard.js
  india_compliance/setup_wizard.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1424 fix: handle nil/exempt items in e-Invoice
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/overrides/test_transaction_data.py
  india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1438 fix: update taxable in patch, continue without gst_accounts
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1451 fix: add zero rated category in transactions for correct reporting
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1461 fix: KeyError in certain transactions resolved by using `get` method for dictionary access.
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1471 fix: allow gst category as deemed export for any gstin type
  india_compliance/gst_india/overrides/party.py
  india_compliance/gst_india/overrides/test_party.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1456 fix: throw error if scheduler is disabled when e-invoice/e-waybill API is used
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/api_classes/e_waybill.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1481 chore: update compatible version
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1473 fix: nil rated supplies in gstr-1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1470 fix: correct gst details
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1448 feat: Export GSTR-1 Excel in one-click & HSN integration in GSTR-1 Report
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1491 fix: include non-existing hsn codes
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1495 fix: patch to update gst treatment in transaction
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_gst_treatment_for_taxable_nil_transaction_item.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1492 refactor: update gst treatment for transactions in more structured way
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/overrides/test_transaction_data.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/test_e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1509 fix: don't execute patch if column is absent or missing gst accounts
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1513 perf: improve item tax template patch
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix
