Repository resilient-tech/india-compliance, pull requests merged in 2023-11, with the labels that each got.

#1227 fix: multiple fixes for purchase reconciliation tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/overrides/email_template.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/utils/gstr/__init__.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_purchase_reco_email_template.py
Labels: backport version-14-hotfix

#1179 feat: GSTR 1 Document Summary Report
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/gstr_1/test_gstr_1.py
Labels: backport version-14-hotfix

#1233 fix: variable declaration in e_waybill_actions
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
Labels: backport version-14-hotfix

#1231 fix: UI changes in E-Invoice and E-waybill
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/public/js/utils.js
Labels: backport version-14-hotfix

#1232 fix: use company name to create address in setup wizard
  india_compliance/setup_wizard.py
Labels: backport version-14-hotfix

#1237 chore: consistent return value for gstin_info
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-14-hotfix

#1240 fix: js typo issues, company fixtures update, uninstall property setters
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/overrides/company.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_company_fixtures.py
Labels: backport version-14-hotfix

#1249 fix: check GL entry permisions for GSTR-1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix

#1248 fix: tax rate not calculating in tax liability gstr-1 report
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix

#1247 fix: alert if ITC is ineligible on validate
  india_compliance/gst_india/overrides/purchase_invoice.py
Labels: backport version-14-hotfix

#1253 fix: escape % for gst accounts name for query builder
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix

#1262 ci(Mergify): automatically merge backport if they pass tests
  .mergify.yml
Labels: backport version-14-hotfix, backport version-15-hotfix

#1265 ci(Mergify): configuration update
  .mergify.yml
Labels: backport version-14-hotfix, backport version-15-hotfix

#1260 test: test cases for advance gst entries
  india_compliance/gst_india/overrides/test_advance_payment_entry.py
  india_compliance/gst_india/utils/tests.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1268 fix: don't process for fuzzy match if bill_no is missing
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1277 fix: update minimum versions
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1280 fix: revert perm check for GST account names
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1276 fix: enhancements for GST on Advance Payment
  india_compliance/gst_india/overrides/payment_entry.py
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/overrides/test_advance_payment_entry.py
  india_compliance/gst_india/overrides/unreconcile_payments.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1132 fix(ux): API Invoice History
  india_compliance/public/js/india_compliance_account/components/invoice_history_table.html
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
  india_compliance/public/js/india_compliance_account/services/AccountService.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1256 fix: E Way Bill for Purchase Receipt
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_applicability.js
  india_compliance/gst_india/client_scripts/purchase_receipt.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/constants/e_waybill.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/purchase_receipt.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/hooks.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix, backport version-15-hotfix

#1294 fix: Resend OTP in Purchase Reconciliation Tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/public/js/utils.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1245 fix: GST Fields and Validations for Supplier Quotation
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/utils/tests.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/check_version_compatibility.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1307 fix: change ewaybill barcode defaults & update python-barcode library version
  india_compliance/gst_india/utils/jinja.py
  india_compliance/patches/check_version_compatibility.py
  pyproject.toml
Labels: backport version-14-hotfix, backport version-15-hotfix

#1305 fix: bulk e-waybill print
  india_compliance/gst_india/client_scripts/sales_invoice_list.js
  india_compliance/gst_india/utils/e_waybill.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1315 chore: update version dependency
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1322 fix: use query builder in hsn_wise_summary
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1331 fix: show value in INR in e-Waybill print format
  india_compliance/gst_india/print_format/e_waybill/e_waybill.html
Labels: backport version-14-hotfix, backport version-15-hotfix

#1321 fix(ux): copy e-waybill fields from DN to SI
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1339 fix: handle NoneType error for vehicle no in e-Waybill api
  india_compliance/gst_india/utils/e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1338 fix: validate mandatory fields and hsn codes for e-Invoice generation
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1349 fix: typo in BoE Summary report
  india_compliance/gst_india/report/bill_of_entry_summary/bill_of_entry_summary.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1353 chore: update compatible version
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1359 fix: use property setter for standard purchase receipt fields
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/patches.txt
  india_compliance/patches/v14/delete_purchase_receipt_standard_custom_fields.py
Labels: backport version-14-hotfix, backport version-15-hotfix
