Repository resilient-tech/india-compliance, pull requests merged in 2024-01, with the labels that each got.

#1525 fix: enqueue gstr3b report
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.js
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.json
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report_list.js
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_default_gstr3b_status.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1472 fix: gl entry voucher type in bill of entry
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
Labels: backport version-15-hotfix

#1532 fix: parse export in correct sequence where it's enqueued
  india_compliance/gst_india/utils/exporter.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1533 fix: failing test case-test_get_document_issued_summary_json fixed
  india_compliance/gst_india/report/gstr_1/test_gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1538 fix: fetch reconciliation status only for purchase
  india_compliance/gst_india/client_scripts/payment_entry.js
  india_compliance/gst_india/overrides/payment_entry.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1555 fix: return if not session_expiry
  india_compliance/gst_india/api_classes/returns.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1552 fix: simplify residual match for more inclusive matches
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1564 fix: gstr-1 hsn wise summary json format
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1563 fix: update reconcilliation status in post install
  india_compliance/install.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1570 fix: return if no nil rated templates
  india_compliance/patches/post_install/update_gst_treatment_for_taxable_nil_transaction_item.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1576 fix: check major version on develop
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1554 fix: allow taxable items with non-taxable items
  india_compliance/gst_india/client_scripts/e_waybill_applicability.js
  india_compliance/gst_india/client_scripts/sales_invoice.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/test_transaction_data.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/gstr_1/test_gstr_1.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: defer-backport

#1447 fix: retry e-waybill creation
  .github/helper/install.sh
  .github/workflows/server-tests.yml
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/data/test_e_waybill.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/set_enable_retry_einv_ewb_generation.py
Labels: squash, defer-backport

#1573 fix: validate invoice no for e-waybill and e-invoice
  india_compliance/gst_india/client_scripts/document_naming_rule.js
  india_compliance/gst_india/client_scripts/document_naming_settings.js
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/overrides/test_sales_invoice.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/public/js/regex_constants.js
  india_compliance/public/js/transaction.js
  india_compliance/public/js/utils.js
Labels: squash, defer-backport

#1609 fix: list appending issue in link_documents method
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1508 feat: schedule e-waybill for extension
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/doctype/e_waybill_log/e_waybill_log.json
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1618 fix: missing arg in a function
  india_compliance/income_tax_india/overrides/asset_depreciation_schedule.py
Labels: backport version-15-hotfix

#1639 fix: avoid setting invalid place of supply
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1645 chore: update pre-commit hooks to latest
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/patches/v14/set_autogenerate_e_waybill_with_e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix, do not squash
