Repository resilient-tech/india-compliance, pull requests merged in 2024-08, with the labels that each got.

#2497 fix: always use `frappe.get_meta` in `set_tax_amount_precisions`
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-15-hotfix

#2485 fix: Mapping of Sales and Purchase Templates
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/hooks.py
Labels: squash, backport version-15-hotfix

#2496 fix: Client-Side Changes Related to Subcontracting
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
Labels: backport version-15-hotfix

#2479 feat(ITC-04): create necessary fields to update original reference
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/client_scripts/subcontracting_receipt.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/patches.txt
Labels: defer-backport

#2511 fix: UX fixes for Taxes in Subcontracting Docs
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.js
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/hooks.py
  india_compliance/public/js/taxes_controller.js
Labels: backport version-15-hotfix

#2505 fix: Respect Company Filter in Purchase Reconciliation Tool
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2522 fix: Link Integration Requests with GST Returns Log
  india_compliance/gst_india/api_classes/taxpayer_returns.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.json
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
Labels: backport version-15-hotfix

#2523 fix: Ignore validation `validate_for_invalid_account_type` for GST category: SEZ
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2556 test: check if post install patches exist
  india_compliance/test_patches.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2564 fix: ignore permissions check for PAN
  india_compliance/gst_india/doctype/pan/pan.py
Labels: backport version-15-hotfix

#2561 fix: value should not be changed after doc is submitted
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/test_subcontracting_transaction.py
  india_compliance/patches.txt
Labels: backport version-15-hotfix

#2568 fix: Remove unused "reason_for_issuing_document" field
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/test_advance_payment_entry.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/remove_old_fields.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2562 fix: adjust depreciation when daily pro-rata is enabled
  india_compliance/income_tax_india/overrides/asset_depreciation_schedule.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2577 fix: Incorrect Fieldname in Query
  india_compliance/gst_india/utils/itc_04/itc_04_data.py
Labels: squash, backport version-15-hotfix

#2555 fix: New GST Category `Input Service Distributor` Introduced
  india_compliance/boot.py
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/patches.txt
  india_compliance/patches/v15/set_default_for_new_gst_category_notification.py
  india_compliance/public/js/india_compliance.bundle.js
  india_compliance/public/js/new_gst_category_notification.js
Labels: backport version-15-hotfix

#2581 fix: validate original references on before_submit hook
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/hooks.py
Labels: backport version-15-hotfix

#2557 fix: ITC Classification Refactor for GST Purchase Register Report
  india_compliance/gst_india/client_scripts/purchase_invoice.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/test_purchase_invoice.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/gst_india/utils/tests.py
  india_compliance/patches.txt
  india_compliance/tests/test_records.json
Labels: squash, backport version-15-hotfix
