Repository resilient-tech/india-compliance, pull requests merged in 2024-02, with the labels that each got.

#1673 fix: Add shipping bill details in gstr_1 exports json
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1612 fix: don't auto-retry in sandbox mode
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1687 fix: validate ecommerce_gstin
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1685 fix: set gst_treatment for nil-rated from item tax template
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1665 fix: set precision for necessary fields in gstr1 report
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1629 fix: only show unreconciled invoice for purchase period
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1607 fix: better ux for e-Invoice and e-Waybill applicability
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_applicability.js
  india_compliance/public/js/utils.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1712 fix: correct tax amount for same item multiple times and precision in item gst detail
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/improve_item_tax_template.py
  india_compliance/patches/v14/update_gst_details_for_invoices_with_same_item_multiple_times.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1718 fix: simpler implementation of itc gls for more consistent gl entries
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1728 fix: set gst breakup only for valid docs
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1735 fix: itc is eligible for export with place of supply 96 and 97
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/purchase_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1724 test: test case to validate property setter
  india_compliance/audit_trail/overrides/test_property_setter.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1736 test: test case for gst settings
  india_compliance/gst_india/doctype/gst_settings/test_gst_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1719 test: e_waybill_log before_print
  india_compliance/gst_india/utils/test_e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1753 chore: more descriptive comment for missing credentials
  india_compliance/gst_india/api_classes/base.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1752 fix: set document type as bill of supply for non-taxable items
  india_compliance/gst_india/data/test_e_waybill.json
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1763 fix: round other charges in e-Invoice
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1766 fix: set filter query for transporter and driver field in PR and PI
  india_compliance/gst_india/client_scripts/purchase_invoice.js
  india_compliance/gst_india/client_scripts/purchase_receipt.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1688 fix: update tds details in tax withholding category
  india_compliance/hooks.py
  india_compliance/income_tax_india/constants/__init__.py
  india_compliance/income_tax_india/constants/custom_fields.py
  india_compliance/income_tax_india/data/tds_details.json
  india_compliance/income_tax_india/overrides/company.py
  india_compliance/income_tax_india/overrides/tax_withholding_category.py
  india_compliance/income_tax_india/setup.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_company_fixtures.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1756 fix: add support for GL Repost for Purchase Invoice ITC Reversal
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/repost_accounting_ledger.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
  india_compliance/hooks.py
  india_compliance/patches.txt
Labels: backport version-15-hotfix

#1758 fix(ux): field `ineligibility_reason` in purchase receipt for better visibility
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/purchase_receipt.py
  india_compliance/hooks.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix, backport version-15-hotfix

#1783 chore: update version compatibility
  india_compliance/gst_india/overrides/repost_accounting_ledger.py
  india_compliance/hooks.py
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1793 fix: ignore mandatory if tds account is not found
  india_compliance/income_tax_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1792 fix: ignore mandatory fields for onload of purchase receipt
  india_compliance/gst_india/overrides/purchase_receipt.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix
