Repository resilient-tech/india-compliance, pull requests merged in 2024-05, with the labels that each got.

#2094 fix: avoid duplicate address keys in gstin info based on key priority
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/test_gstin_info.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2102 fix(ic page): theme of India compliance page similar to v15
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
  india_compliance/public/js/india_compliance_account/pages/AuthPage.vue
  india_compliance/public/scss/india_compliance_account.bundle.scss
Labels: backport version-15-hotfix

#2108 fix: condition for b2cl in gstr-1 data
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2104 fix: update tax rounding difference in the last item
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#2116 fix: handle empty place of supply in GST Sales Register Beta Report
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2121 fix: complete minor todo's and fixes, update links to documentation
  README.md
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstr_import_log/gstr_import_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/overrides/address.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/gst_india/utils/gstr_2/gstr.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2a.py
  india_compliance/patches/post_install/add_company_link_to_einvoice_settings.py
  india_compliance/patches/post_install/update_gst_accounts.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2142 fix: include items without HSN Code in outward hsn summary
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2117 fix: support custom print format for e-Waybill
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/uninstall.py
  india_compliance/gst_india/utils/e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2151 fix: add description and hide progress bar in purchase reconciliation tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/utils/gstr_2/__init__.py
Labels: p1, backport version-14-hotfix, backport version-15-hotfix

#2145 fix: Purchase Reconciliation data not generated error handling
  india_compliance/gst_india/api_classes/returns.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/patches.txt
  india_compliance/patches/v14/delete_not_generated_gstr_import_log.py
Labels: p1

#2150 fix: include Nil-Rated Exports in GSTR-1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2147 fix: GST inward supply should be updated every time the linked document is canceled
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/patches.txt
  india_compliance/patches/v14/unset_inward_supply_link_for_cancelled_purchase.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2057 fix: add `match_found` in reconciliation status and patch
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/patches.txt
  india_compliance/patches/v14/add_match_found_in_purchase_reconciliation_status.py
  india_compliance/public/js/utils.js
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2171 fix: non-group tds payable account for tax withholding category
  india_compliance/income_tax_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2170 fix: exclude place of supply for impg in purchase reco
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2172 fix: handle empty GSTIN value in `get_pan_level_data` method
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2159 fix: resolved discrepancy in function arguments for depreciation calcu…
  india_compliance/income_tax_india/overrides/asset_depreciation_schedule.py
Labels: squash, backport version-15-hotfix

#2158 fix: exclude same gstin transactions from gstr3b
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2144 fix: use base_tax_amount_after_discount_amount instead of tax_amount
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2190 refactor: setup default property setters
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/uninstall.py
  india_compliance/gst_india/utils/e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2194 fix: Dynamic Link for Purchase Doc in Purchase Reco
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/public/js/purchase_reconciliation_tool/data_table_manager.js
Labels: backport version-14-hotfix, backport version-15-hotfix
