Repository resilient-tech/india-compliance, pull requests merged in 2024-07, with the labels that each got.

#2321 fix: show validity date section only if date is availbale in IC Page
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
Labels: backport version-14-hotfix, backport version-15-hotfix

#2317 fix: report -ve other charges as discount for e-Waybill and e-Invoice
  india_compliance/gst_india/utils/transaction_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2063 feat: RCM for Sales Transaction
  india_compliance/gst_india/client_scripts/item_tax_template.js
  india_compliance/gst_india/data/tax_defaults.json
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/doctype/gst_account/gst_account.json
  india_compliance/gst_india/doctype/gst_settings/test_gst_settings.py
  india_compliance/gst_india/overrides/company.py
  india_compliance/gst_india/overrides/item_tax_template.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/test_item_tax_template.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_gst_accounts.py
  india_compliance/patches/post_install/update_itc_amounts.py
  india_compliance/patches/v14/rename_reverse_charge_to_purchase_reverse_charge.py
  india_compliance/patches/v14/set_correct_root_account_for_rcm.py
Labels: p1, backport version-14-hotfix, backport version-15-hotfix

#2336 fix: do not execute patch if field does not exists
  india_compliance/patches/v15/migrate_print_options_to_new_field.py
Labels: backport version-15-hotfix

#2344 fix: return payment entries if no taxes in regional override
  india_compliance/gst_india/overrides/payment_entry.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2340 feat: introduce new APIs for e-Invoice data
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/taxpayer_base.py
  india_compliance/gst_india/api_classes/taxpayer_e_invoice.py
  india_compliance/gst_india/api_classes/taxpayer_returns.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/gst_india/utils/gstr_utils.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2367 fix: check equality to avoid iteration error
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2373 fix: remove post install patch not implemented
  india_compliance/install.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2392 fix: Update Taxes for Items
  india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2379 fix: section 9(5) of 3.1.1 of gstr_3b
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.html
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report_template.json
  india_compliance/gst_india/doctype/gstr_3b_report/test_gstr_3b_report.py
  india_compliance/gst_india/utils/tests.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2361 feat: suggest default `HSN` in item from item group
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/patches.txt
  india_compliance/public/js/quick_entry.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2407 fix: format `Creation Date` in Audit Trail
  india_compliance/audit_trail/report/audit_trail/audit_trail.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2408 fix: Add draft count to cancelled count in GSTR-1 and GSTR-1 Beta excel export
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2397 fix: optimise function `update_gst_category`
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2420 fix: correct validation for reverse charge returns
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2421 fix: minor changes for gl entries in line with changes in ERPNext
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
Labels: backport version-15-hotfix

#2425 fix(gstr-1): recompute books data every time data is sync with gstin
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2434 fix: disable cron jobs as per settings
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/stop_unnecessary_scheduled_jobs.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2441 test: load from db for testing repost entries
  india_compliance/gst_india/overrides/test_ineligible_itc.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2440 fix: display registered email address in IC account
  india_compliance/public/js/india_compliance_account/pages/AccountPage.vue
Labels: backport version-14-hotfix, backport version-15-hotfix

#2210 feat: E-WayBill for Subcontracting
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/client_scripts/e_waybill_applicability.js
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/client_scripts/subcontracting_order.js
  india_compliance/gst_india/client_scripts/subcontracting_receipt.js
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/constants/e_waybill.py
  india_compliance/gst_india/data/test_e_waybill.json
  india_compliance/gst_india/doctype/e_waybill_log/e_waybill_log.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/india_compliance_taxes_and_charges/__init__.py
  india_compliance/gst_india/doctype/india_compliance_taxes_and_charges/india_compliance_taxes_and_charges.json
  india_compliance/gst_india/doctype/india_compliance_taxes_and_charges/india_compliance_taxes_and_charges.py
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/print_format/e_waybill/e_waybill.html
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/taxes_controller.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/public/js/india_compliance.bundle.js
  india_compliance/public/js/taxes_controller.js
  india_compliance/public/js/transaction.js
  india_compliance/public/scss/india_compliance.bundle.scss
Labels: p1, backport version-15-hotfix

#2468 fix: use company default currency in report
  india_compliance/gst_india/report/bill_of_entry_summary/bill_of_entry_summary.py
  india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.py
  india_compliance/gst_india/report/gst_advance_detail/gst_advance_detail.py
  india_compliance/gst_india/report/gst_balance/gst_balance.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2406 fix: add `E-commerce Sales` filter to Sales Register Beta Report
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.js
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/report/gst_sales_register_beta/test_sales_register_beta.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2452 fix: Handle error 2283 while generating e-Invoice
  india_compliance/gst_india/api_classes/taxpayer_e_invoice.py
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/test_e_invoice.py
Labels: squash, backport version-15-hotfix

#2433 refactor: GSTR-1 Beta and make it extensible for other returns
  india_compliance/gst_india/doctype/gst_return_log/__init__.py
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.js
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.json
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gst_return_log/test_gst_return_log.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
  india_compliance/patches.txt
  india_compliance/patches/v15/migrate_gstr1_log_to_returns_log.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2488 fix: gst invoice warning based on gst_tax_type
  india_compliance/gst_india/client_scripts/sales_invoice.js
Labels: backport version-14-hotfix, backport version-15-hotfix
