Repository resilient-tech/india-compliance, pull requests merged in 2024-04, with the labels that each got.

#1960 test: Create fiscal year in Purchase Reconciliation Tool test case
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1970 fix(ux): better error message
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1975 fix(minor): allow 673 like pin code for puducherry
  india_compliance/gst_india/constants/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1986 fix(minor): ReferenceError: taxes_table is not defined in Journal Entry
  india_compliance/gst_india/client_scripts/expense_claim.js
  india_compliance/gst_india/client_scripts/journal_entry.js
Labels: backport version-15-hotfix

#1968 fix: Handle If `response_json` Is `None`
  india_compliance/gst_india/api_classes/base.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1979 test: test cases for `update item after submit` in Sales Order and Purchase Order
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1994 fix: missing gst amounts in hsn json
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1995 chore: use similar color for all number cards
  india_compliance/gst_india/number_card/invoice_cancelled_but_not_e_invoice/invoice_cancelled_but_not_e_invoice.json
  india_compliance/gst_india/number_card/pending_e_invoices/pending_e_invoices.json
  india_compliance/gst_india/number_card/pending_e_waybill/pending_e_waybill.json
  india_compliance/public/js/custom_number_card.js
  india_compliance/public/js/india_compliance.bundle.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2002 fix: group overview in GST sales register beta by category
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.js
  india_compliance/gst_india/utils/gstr/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1966 fix: group tax values and amounts for invoice print formats
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2009 fix: validate for cess non-advol
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1965 test: test cases for gst sales register beta report
  india_compliance/gst_india/doctype/bill_of_entry/test_bill_of_entry.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.js
  india_compliance/gst_india/report/gst_sales_register_beta/test_sales_register_beta.py
  india_compliance/gst_india/utils/gstr/gstr_1.py
  india_compliance/gst_india/utils/tests.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2022 fix(minor): better way to override totals in gst sales beta report
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2019 fix: uom as per gst
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/gstr/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2027 refactor: GSTR 1 and GSTR 2 utilities made independent
  india_compliance/gst_india/doctype/gstr_import_log/gstr_import_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/gst_india/utils/gstr_2/gstr.py
  india_compliance/gst_india/utils/gstr_2/gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/gstr_2b.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b.py
  india_compliance/gst_india/utils/gstr_utils.py
  india_compliance/hooks.py
  india_compliance/public/js/utils.js
Labels: defer-backport

#2032 fix(excel): remove default bg colors from excel export
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/utils/exporter.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2028 fix: Document Type as `CHL` in case of return Invoice with Nil-rated
  india_compliance/gst_india/utils/e_waybill.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2045 fix: cancel sales invoice if e-Invoice is cancelled
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2046 fix: handle on cancel for reco tool
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2041 fix: avoid_duplicate in address
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2070 perf: dont create address copy
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2056 fix(auto-rcm): tds getting overwritten where rcm template was reset
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2077 fix: avoiding addition of TDS rates for past financial year
  india_compliance/income_tax_india/data/tds_details.json
  india_compliance/income_tax_india/overrides/company.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2066 fix: support tax collector as customer
  india_compliance/gst_india/client_scripts/party.js
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/overrides/test_party.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/test_gstin_info.py
  india_compliance/patches.txt
  india_compliance/public/js/regex_constants.js
  india_compliance/public/js/utils.js
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2088 fix: Remove check digit validation for transporter id
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix
