Repository resilient-tech/india-compliance, pull requests merged in 2024-06, with the labels that each got.

#2197 fix: ineligible ITC due to Pos value in GSTR3b
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2209 fix: handle cases where public key is invalided
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/returns.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2112 feat: GSTR-1 Beta for filing
  india_compliance/gst_india/api_classes/public.py
  india_compliance/gst_india/api_classes/returns.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstin/gstin.json
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/gst_india/doctype/gstr_1_beta/__init__.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.css
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_detail_comparision.html
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/doctype/gstr_1_beta/test_gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_log/__init__.py
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.js
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.json
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.py
  india_compliance/gst_india/doctype/gstr_1_log/test_gstr_1_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/overrides/payment_entry.py
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/report/gst_sales_register_beta/test_sales_register_beta.py
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/exporter.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_utils.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_default_gstr1_settings.py
  india_compliance/public/js/components/data_table_manager.js
  india_compliance/public/js/components/filter_group.js
  india_compliance/public/js/components/number_card.js
  india_compliance/public/js/components/set_gstin_options.js
  india_compliance/public/js/components/view_group.js
  india_compliance/public/js/gstr1.bundle.js
  india_compliance/public/js/purchase_reconciliation_tool.bundle.js
  india_compliance/public/js/purchase_reconciliation_tool/purchase_reconciliation_tool.bundle.js
  india_compliance/public/js/utils.js
  india_compliance/tests/__init__.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2220 feat: GSTR-1 Beta for filing (#2112)
  india_compliance/gst_india/api_classes/public.py
  india_compliance/gst_india/api_classes/returns.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstin/gstin.json
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/gst_india/doctype/gstr_1_beta/__init__.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.css
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_detail_comparision.html
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/doctype/gstr_1_beta/test_gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_log/__init__.py
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.js
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.json
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.py
  india_compliance/gst_india/doctype/gstr_1_log/test_gstr_1_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/overrides/payment_entry.py
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/report/gst_sales_register_beta/test_sales_register_beta.py
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/exporter.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_utils.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_default_gstr1_settings.py
  india_compliance/public/js/components/data_table_manager.js
  india_compliance/public/js/components/filter_group.js
  india_compliance/public/js/components/number_card.js
  india_compliance/public/js/components/set_gstin_options.js
  india_compliance/public/js/components/view_group.js
  india_compliance/public/js/gstr1.bundle.js
  india_compliance/public/js/purchase_reconciliation_tool.bundle.js
  india_compliance/public/js/purchase_reconciliation_tool/purchase_reconciliation_tool.bundle.js
  india_compliance/public/js/utils.js
  india_compliance/tests/__init__.py
Labels: backport version-14-hotfix

#2211 chore: Update conditions
  india_compliance/gst_india/report/gst_itemised_sales_register/gst_itemised_sales_register.py
Labels: backport version-15-hotfix

#2226 fix: correct upload status for GSTR-1 books
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/patches/v14/update_default_gstr1_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2205 fix: do not include exports without payment Purchase Invoices in GSTR3b.
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
Labels: p1

#2233 fix: positive values for cdnr in gstr-1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2125 feat: section to report e-commerce sale through GSTR-1
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/set_default_gst_settings.py
  india_compliance/patches/v14/enable_sales_through_ecommerce_operator.py
  india_compliance/public/js/transaction.js
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2245 fix: `DoesNotExistError` while processing return info
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_log/gstr_1_log.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2241 fix: add gst_tax_type field
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/doctype/bill_of_entry_taxes/bill_of_entry_taxes.json
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/payment_entry.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/hooks.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/set_gst_tax_type.py
Labels: p1, backport version-14-hotfix, backport version-15-hotfix

#2281 feat: support ecommerce sale from GSTR-1 (backport: #2125)
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/set_default_gst_settings.py
  india_compliance/patches/v14/enable_sales_through_ecommerce_operator.py
  india_compliance/public/js/transaction.js
Labels: backport version-14-hotfix

#2287 fix: allow address in india with overseas category for high sea sales
  india_compliance/gst_india/overrides/address.py
  india_compliance/gst_india/overrides/party.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2206 fix(ineligible itc): update GL's with valuation hook, refactor
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/purchase_receipt.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/hooks.py
  india_compliance/patches/check_version_compatibility.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2303 fix: return if no gst accounts in advance payment tax reversal
  india_compliance/gst_india/overrides/payment_entry.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2314 fix: round taxes in last taxable item
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix
