Repository resilient-tech/india-compliance, pull requests merged in 2024-03, with the labels that each got.

#1806 fix: remove validation for duplicate tax withholding category
  india_compliance/hooks.py
  india_compliance/income_tax_india/overrides/company.py
  india_compliance/income_tax_india/overrides/tax_withholding_category.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1818 fix: return silently on onload for ignore_gst_validations(temprory fix)
  india_compliance/gst_india/overrides/purchase_receipt.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#1813 fix: overseas category is always interstate
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1686 fix: simplify e-invoice summary report
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/number_card/invoice_cancelled_but_not_e_invoice/invoice_cancelled_but_not_e_invoice.json
  india_compliance/gst_india/number_card/number_card.py
  india_compliance/gst_india/number_card/pending_e_invoices/pending_e_invoices.json
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.js
  india_compliance/gst_india/report/e_invoice_summary/e_invoice_summary.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_e_invoice_status.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1833 fix: ensure links exist before setting default values for GST fields in Address
  india_compliance/gst_india/client_scripts/address.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1819 test: test case to validate accounts settings
  india_compliance/audit_trail/overrides/test_account_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1815 test: test case for gst settings
  india_compliance/gst_india/doctype/gst_settings/test_gst_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1829 fix: validate correctness of Item wise tax details if tax type is actual
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/tests.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1827 fix: set rcm taxes in `validate` instead of `before_validate`
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1846 fix(ux): better message for version compatibility
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1849 fix: correct condition for can extend e-waybill
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/utils/e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1624 fix: validate gst_transporter_id
  india_compliance/gst_india/api_classes/e_waybill.py
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/client_scripts/supplier.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/gst_india/doctype/gstin/test_gstin.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/public/js/transaction.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1854 fix: extending accounts in tax withholding category
  india_compliance/income_tax_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1437 feat: auto-reconcile purchases with GSTR2A
  india_compliance/gst_india/api_classes/returns.py
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_detail_comparision.html
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/gstr/__init__.py
  india_compliance/gst_india/utils/gstr/gstr.py
  india_compliance/hooks.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_default_auto_reconciliation_settings.py
  india_compliance/public/js/utils.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1873 fix(ux): suggest custom cancel message based on original document type
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1871 fix: include TDS regex in GSTIN regex
  india_compliance/gst_india/client_scripts/party.js
  india_compliance/public/js/regex_constants.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#1885 fix: validate inconsistent gst treatment with item taxes
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1869 fix: added TDS on Purchasing in Tax Withholding Category
  india_compliance/income_tax_india/constants/__init__.py
  india_compliance/income_tax_india/data/tds_details.json
  india_compliance/patches.txt
Labels: backport version-14-hotfix, backport version-15-hotfix

#1893 fix: use text editor for gst breakup table instead of long text
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/patches.txt
  india_compliance/templates/gst_breakup.html
Labels: backport version-14-hotfix, backport version-15-hotfix

#1791 ci: allow workflow call for other projects to use
  .github/workflows/codeql.yml
  .github/workflows/linters.yml
  .github/workflows/server-tests.yml
Labels: backport version-14-hotfix, backport version-15-hotfix

#1900 fix: ignore mandatory when creating or updating tax witholding category
  india_compliance/income_tax_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1905 fix(minor): keeps gst accounts in GST Settings as non-mandatory
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#1912 fix(minor): add fallback to stock received but not billed account for ineligible itc
  india_compliance/gst_india/overrides/ineligible_itc.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1918 fix: correct export type condition for SEZ in GSTR-1
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1921 fix: revert tax breakup calculation for backwards compatibility (with print format)
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix

#1923 fix: recalculate gst details for gst breakup if group_same_items is True
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1937 fix: ensure `gst_rate` is a float value
  india_compliance/gst_india/overrides/item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#1938 test: fix failing test cases related to UOM validation in ERPNext
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/utils/test_e_waybill.py
Labels: squash

#1933 fix: return silently in ignore_gst_validations
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix

#1926 feat: GST Sales Register Beta Report
  india_compliance/gst_india/report/gst_sales_register_beta/__init__.py
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.js
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.json
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/utils/gstr/gstr_1.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
  india_compliance/public/js/quick_info_popover.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#1943 fix: update `taxable value` on updating items after submitting Sales Order and Purchase Order
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix
