Repository resilient-tech/india-compliance, pull requests merged in 2024-12, with the labels that each got.

#2783 test: additional tests recommendation for sub contracting order
  india_compliance/gst_india/overrides/test_subcontracting_transaction.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/gst_india/utils/tests.py
Labels: backport version-15-hotfix

#2803 fix: Only Validate Taxes if e-Waybill Applicable
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/client_scripts/subcontracting_order.js
  india_compliance/gst_india/client_scripts/subcontracting_receipt.js
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/hooks.py
  india_compliance/public/js/utils.js
Labels: backport version-15-hotfix

#2826 fix: use bulk insert to ignore validations
  india_compliance/patches/v15/migrate_boe_taxes_to_ic_taxes.py
Labels: backport version-15-hotfix

#2835 fix: failing test case of payment entry
  india_compliance/gst_india/overrides/payment_entry.py
Labels: backport version-15-hotfix

#2830 fix: taxable value for invoice without qty and value
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2836 fix: correct categorisation of is_export and fetching taxes accordingly
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2831 fix(patch): ignore validate when creating item tax template
  india_compliance/patches/post_install/improve_item_tax_template.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2810 fix: add documentation links in help
  india_compliance/public/js/help_links.js
  india_compliance/public/js/india_compliance.bundle.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2832 fix: Error Handling for download of GSTR2A/2B
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2859 chore: compatibiltiy for erpnext
  india_compliance/patches/check_version_compatibility.py
Labels: backport version-15-hotfix

#2799 fix: use shipping address instread of port address for e-invoice
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2839 fix: Fields to identify from where document is downloaded
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json
  india_compliance/gst_india/utils/gstr_2/gstr.py
  india_compliance/gst_india/utils/gstr_2/gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/gstr_2b.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b_v3_0.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b_v4_0.py
  india_compliance/patches.txt
  india_compliance/patches/v15/set_download_document_for_2a_2b.py
Labels: squash, backport version-15-hotfix

#2864 fix: show error message instead of throw during Purchase Invoice name validation
  india_compliance/gst_india/overrides/test_purchase_invoice.py
  india_compliance/gst_india/overrides/test_sales_invoice.py
  india_compliance/gst_india/utils/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2870 fix: update minimum and maximum net rate field in item
  india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.js
  india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py
  india_compliance/gst_india/overrides/item.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2874 fix: Remove Filter on Second Click
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/public/js/components/filter_group.js
Labels: backport version-15-hotfix

#2879 fix: validate item tax template item_name wise if item_code is not set
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2888 fix: ignore root company validation
  india_compliance/gst_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2896 fix: ignore system error that randomly comes for section CDNR
  india_compliance/gst_india/api_classes/taxpayer_returns.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2895 fix: set reconciliation status for manual match in purchase reco tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/patches.txt
  india_compliance/patches/v14/set_reconciliation_status_for_manual_match.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2902 fix: Tax Category Required to Set Item Tax Template
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/patches.txt
Labels: p1, backport version-15-hotfix
