Repository resilient-tech/india-compliance, pull requests merged in 2024-11, with the labels that each got.

#2645 fix: handle `Invalid GSTIN` error
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/api_classes/public.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/test_gstin_info.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2671 fix: allow selection of stock entry from multiple subcontracting orders
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/client_scripts/subcontracting_receipt.js
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/gst_india/utils/itc_04/itc_04_data.py
Labels: squash

#2694 fix: create custom field in fee category doctype
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/overrides/fee_category.py
  india_compliance/gst_india/overrides/item.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/uninstall.py
  india_compliance/hooks.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/uninstall.py
Labels: backport version-15-hotfix

#2699 fix: set filing status to processed
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
Labels: backport version-15-hotfix

#2701 fix(gstr1): multiple fixes related to filing of gstr-1
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
Labels: backport version-15-hotfix

#2705 fix: added missing return statement for uploading draft invoices
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
Labels: backport version-15-hotfix

#2712 fix: conditionally update b2c limit as per changes in law
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2716 fix: include "140" pincode series for chandigarh
  india_compliance/gst_india/constants/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2728 fix: pass correct Company GSTIN
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2732 fix: validate hsn code for both e-waybill and e-invoice
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2722 fix: pos from shipping address based on account settings
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/patches.txt
Labels: backport version-15-hotfix

#2723 fix: Items Table Removed from Invoice Data
  india_compliance/db_utils.py
  india_compliance/gst_india/data/test_gstr_2b_v3_0.json
  india_compliance/gst_india/data/test_gstr_2b_v4_0.json
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py
  india_compliance/gst_india/utils/gstr_2/gstr.py
  india_compliance/gst_india/utils/gstr_2/gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/gstr_2b.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2B_v4_0.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b_v3_0.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_total_taxes_for_gst_inward_supply.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix

#2727 fix: updated item tax template query
  india_compliance/public/js/taxes_controller.js
Labels: backport version-15-hotfix

#2756 fix: ensure shipping details are visible and exported for GSTR-1 beta
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2755 fix: Company GSTIN Should be Mandatory as Supplier can be Unregistered
  india_compliance/gst_india/client_scripts/e_waybill_applicability.js
  india_compliance/gst_india/client_scripts/stock_entry.js
  india_compliance/gst_india/overrides/subcontracting_transaction.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-15-hotfix

#2786 chore: use `placeholder` to mask sensitive info
  india_compliance/gst_india/api_classes/base.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2785 fix: auto set link doctype and docname in address dialog for lead
  india_compliance/public/js/quick_entry.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2762 refactor: Changed `GSTIN` description html
  india_compliance/public/js/utils.js
Labels: squash, do not backport

#2784 fix: always check for company gstin
  india_compliance/gst_india/overrides/subcontracting_transaction.py
Labels: backport version-15-hotfix

#2770 fix: Take up Company type from GSTIN portal automatically
  india_compliance/public/js/quick_entry.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2800 fix: show correct number of documents for purchase recon tool for missing in 2A/2B
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_detail_comparision.html
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
Labels: backport version-14-hotfix, backport version-15-hotfix
