Repository resilient-tech/india-compliance, pull requests merged in 2025-07, with the labels that each got.

#3502 fix: avoid undefined gst_hsn_code check when item_code is missing
  india_compliance/gst_india/client_scripts/purchase_invoice.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#3326 feat: use standard APIs for e-Invoice and e-Waybill
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/api_classes/e_waybill.py
  india_compliance/gst_india/api_classes/nic/__init__.py
  india_compliance/gst_india/api_classes/nic/auth.py
  india_compliance/gst_india/api_classes/nic/e_invoice.py
  india_compliance/gst_india/api_classes/nic/e_waybill.py
  india_compliance/gst_india/api_classes/nic/e_waybill_errors.py
  india_compliance/gst_india/api_classes/nic/test_auth.py
  india_compliance/gst_india/api_classes/public.py
  india_compliance/gst_india/api_classes/taxpayer_base.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/patches.txt
Labels: squash, backport version-15-hotfix

#3508 fix: add TDS section 192B
  india_compliance/income_tax_india/constants/__init__.py
  india_compliance/patches.txt
Labels: backport version-15-hotfix

#3523 fix: handle None values in date transformation for GSTR-1 export
  india_compliance/gst_india/doctype/gstr_1/gstr_1_export.py
Labels: backport version-15-hotfix

#3531 refactor: replace Jinja {% include %} with doctype_js hook for loading JS
  india_compliance/gst_india/client_scripts/address.js
  india_compliance/gst_india/client_scripts/company.js
  india_compliance/gst_india/client_scripts/customer.js
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
  india_compliance/gst_india/client_scripts/supplier.js
  india_compliance/hooks.py
Labels: backport version-15-hotfix

#3542 fix: handle auth failure while generating evc otp
  india_compliance/gst_india/api_classes/taxpayer_base.py
  india_compliance/gst_india/utils/gstr_utils.py
  india_compliance/public/js/gst_api_handler.js
Labels: backport version-15-hotfix

#3546 fix: add support for identifying Indian registered companies in GST validation in JS;
  india_compliance/boot.py
  india_compliance/gst_india/client_scripts/purchase_invoice.js
  india_compliance/public/js/transaction.js
  india_compliance/public/js/utils.js
Labels: squash, backport version-14-hotfix, backport version-15-hotfix
