Repository resilient-tech/india-compliance, pull requests merged in 2025-03, with the labels that each got.

#3106 fix: use respective party's name instead of document name
  india_compliance/gst_india/report/gstin_status/gstin_status.py
Labels: backport version-15-hotfix

#3115 fix: Allow Reclaim of ITC Reversal
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.html
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/setup/property_setters.py
  india_compliance/patches.txt
Labels: backport version-14-hotfix, backport version-15-hotfix

#3112 fix: Minor Fixes related to IMS and Purchase Reco Tool
  india_compliance/gst_india/doctype/e_invoice_log/e_invoice_log.json
  india_compliance/gst_india/doctype/e_waybill_log/e_waybill_log.json
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.js
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/utils/gstr_2/gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b_v3_0.py
  india_compliance/gst_india/utils/gstr_2/test_gstr_2b_v4_0.py
  india_compliance/patches.txt
  india_compliance/patches/v15/update_supplier_filing_status.py
  india_compliance/public/js/reconciliation_components/tabs.js
  india_compliance/public/js/utils.js
Labels: backport version-15-hotfix

#3116 fix: Use `UOM` instead of `Stock UOM `for consistency
  india_compliance/gst_india/report/gst_sales_register_beta/gst_sales_register_beta.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/test_hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3085 fix: Restrict M1 and M2 for quarterly preference
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/gstr_download_history.html
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
Labels: backport version-15-hotfix

#3126 fix: Ignore `No Records Found` Error
  india_compliance/gst_india/api_classes/public.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.js
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-15-hotfix

#2932 fix: Support creation of BOE against more than one purchase invoice
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.js
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/doctype/bill_of_entry_item/bill_of_entry_item.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/overrides/ineligible_itc.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/overrides/test_ineligible_itc.py
  india_compliance/gst_india/report/bill_of_entry_summary/bill_of_entry_summary.py
  india_compliance/patches.txt
  india_compliance/patches/v15/multiple_pi_in_boe.py
Labels: squash, p1

#3136 fix: issue with increment and naming of GST Inward Supply
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#3153 test: Incorrect Purchase Reconciliation Tool Test Case and Data
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py
Labels: backport version-15-hotfix

#3158 fix: don't validate GST settings during installation
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3147 refactor: move `is_gstr1_api_enabled` function to gst settings
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3154 fix: Restrict Sales Invoice Cancellation if e-Invoice not Cancellable
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/test_e_invoice.py
Labels: backport version-15-hotfix

#3155 fix: Purchase Reconciliation Tool with additional export columns
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/gst_invoice_management_system/__init__.py
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/public/js/reconciliation_components/tabs.js
Labels: backport version-15-hotfix

#3173 fix: add Trans. Doc No. and Dt. in e-Waybill detailed print format
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.html
Labels: backport version-15-hotfix

#3181 fix: disable gstin status validation by default
  india_compliance/gst_india/setup/__init__.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3179 Fix: Handle NoneType HSN code check during `Download JSON`
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3196 fix: Use Posting Date if Bill Date is Empty
  india_compliance/gst_india/doctype/gst_invoice_management_system/__init__.py
Labels: backport version-15-hotfix

#3200 fix: Incorrect Field Mapping for Total Tax
  india_compliance/gst_india/report/gst_sales_register_beta/test_sales_register_beta.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3198 fix: Handle Refund for e-Invoice
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/data/tax_defaults.json
  india_compliance/gst_india/doctype/gst_account/gst_account.json
  india_compliance/gst_india/overrides/company.py
  india_compliance/gst_india/overrides/item_tax_template.py
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_data.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/transaction_data.py
  india_compliance/setup_wizard.py
Labels: squash, backport version-15-hotfix

#3211 fix: check if settings are enabled for transporter id check
  india_compliance/gst_india/doctype/gstin/gstin.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3217 fix: handle non existing value with empty string
  india_compliance/gst_india/print_format/e_waybill/e_waybill.html
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.html
Labels: backport version-14-hotfix, backport version-15-hotfix

#3223 fix: Set Default Month and Year in GSTR-3B Reports
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.js
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.js
  india_compliance/public/js/utils.js
Labels: backport version-15-hotfix

#3225 fix: Include Advances Received or Adjusted in GSTR3B 3.1(a)
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3237 fix: leap year check logic
  india_compliance/income_tax_india/overrides/asset_depreciation_schedule.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3231 fix: Apply Precision for Purchase Invoice to Inward Supply Matching
  india_compliance/gst_india/overrides/purchase_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3232 refactor: Remove ITC Amount Fields and Use GST Details
  india_compliance/gst_india/constants/custom_fields.py
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
  india_compliance/gst_india/overrides/purchase_invoice.py
  india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py
  india_compliance/install.py
  india_compliance/patches.txt
  india_compliance/patches/post_install/update_itc_amounts.py
  india_compliance/patches/v15/remove_itc_amount_custom_fields.py
Labels: squash, backport version-15-hotfix
