Repository resilient-tech/india-compliance, pull requests merged in 2025-05, with the labels that each got.

#3364 fix(gstr-1 beta): change to long queue due to timeout
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
Labels: p1, backport version-15-hotfix

#3361 fix: prefer tradename for GST Registrations of HUF
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3314 fix: date comparison in cancel_e_waybill_e_invoice function
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/test_e_invoice.py
Labels: p1, backport version-15-hotfix

#3368 fix: proper filtering of `PI` for `Bill Of Entry`
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.js
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
Labels: p1, backport version-15-hotfix

#3370 fix: update tds details for financial year 2025-26
  india_compliance/income_tax_india/constants/__init__.py
  india_compliance/income_tax_india/data/tds_details.json
  india_compliance/patches.txt
  india_compliance/patches/v14/update_tax_withholding_categories.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#3355 fix: insert account with ignoring mandatory fields
  india_compliance/gst_india/overrides/company.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3387 fix: set company_gstin value unconditionally in purchase reco
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/public/js/reconciliation_components/actions.js
Labels: backport version-14-hotfix, backport version-15-hotfix
