Repository resilient-tech/india-compliance, pull requests merged in 2025-04, with the labels that each got.

#3248 refactor: Use GST Details in GSTR3B Report
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py
Labels: backport version-15-hotfix

#3252 fix: dont try to deserialize a blank response
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-15-hotfix

#3256 fix: Test Cases
  india_compliance/gst_india/report/gstr_1/test_gstr_1.py
  india_compliance/gst_india/utils/itc_04/test_itc_04_export.py
Labels: backport version-15-hotfix

#2584 feat: GST Purchase Register Beta Report
  india_compliance/gst_india/report/gst_purchase_register_beta/__init__.py
  india_compliance/gst_india/report/gst_purchase_register_beta/gst_purchase_register_beta.js
  india_compliance/gst_india/report/gst_purchase_register_beta/gst_purchase_register_beta.json
  india_compliance/gst_india/report/gst_purchase_register_beta/gst_purchase_register_beta.py
  india_compliance/gst_india/utils/gstr3b/gstr3b_data.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
Labels: squash, backport version-15-hotfix

#3270 fix: Set Company Address to Prevent Incorrect Address Assignment
  india_compliance/gst_india/report/gstr_1/test_gstr_1.py
Labels: backport version-15-hotfix

#3266 chore: removed redundant column break from e-Waybill Log doctype
  india_compliance/gst_india/doctype/e_waybill_log/e_waybill_log.json
Labels: backport version-14-hotfix

#3271 fix: validate same party gstin based on document field in subcontracting transaction
  india_compliance/gst_india/overrides/subcontracting_transaction.py
Labels: backport version-15-hotfix

#3264 fix: do not auto apply rcm if place of supply is not set
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3280 fix: correct data format for error response for hsn data upload
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3260 feat: GST Tax Rate-Wise Summary Report
  india_compliance/gst_india/report/gst_tax_rate_wise_summary/__init__.py
  india_compliance/gst_india/report/gst_tax_rate_wise_summary/gst_tax_rate_wise_summary.js
  india_compliance/gst_india/report/gst_tax_rate_wise_summary/gst_tax_rate_wise_summary.json
  india_compliance/gst_india/report/gst_tax_rate_wise_summary/gst_tax_rate_wise_summary.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
Labels: squash

#3227 refactor: Use GST Details for e-Waybill and e-Invoice Transactions
  india_compliance/gst_india/utils/transaction_data.py
Labels: squash, do not backport

#3288 fix: support same item with different tax rates
  india_compliance/gst_india/overrides/test_transaction.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/test_hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/utils/taxes_controller.py
Labels: backport version-15-hotfix

#3279 fix: add backdated e-invoice validation and exception handling
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_default_e_invoice_time_limit.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3293 revert: use shipping address instead of port address for e-invoice
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3298 fix: callback parameter in create_or_update_gstin_status function
  india_compliance/gst_india/doctype/gstin/gstin.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3301 fix: consistency in supply type and select options for GST Inward Supply
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#3304 fix: remove `GSTIN` status update error
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/gst_india/report/gstin_status/gstin_status.js
Labels: squash, backport version-15-hotfix

#3316 fix: don't update existing default Property Setters on patch run
  india_compliance/gst_india/setup/property_setters.py
Labels: backport version-15-hotfix

#3330 fix: dont hardcode precision
  india_compliance/gst_india/overrides/ineligible_itc.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3312 refactor: improve selecting date range
  india_compliance/audit_trail/report/audit_trail/audit_trail.js
  india_compliance/audit_trail/report/audit_trail/audit_trail.py
Labels: backport version-15-hotfix

#3323 fix: update valuation rate after item gst details are updated
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/overrides/transaction.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3315 fix: otp handling in e-invoice for taxpayer API
  india_compliance/gst_india/client_scripts/e_invoice_actions.js
  india_compliance/gst_india/utils/e_invoice.py
Labels: backport version-15-hotfix

#3327 fix: uom for service item as "NA"
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3321 fix: include only Taxable and Zero-Rated supplies for taxable value in Purchase reco tool
  india_compliance/gst_india/constants/__init__.py
  india_compliance/gst_india/data/test_purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: squash

#3320 fix: Validate GST HSN Code for JSON Upload/Download
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/test_hsn_wise_summary_of_outward_supplies.py
Labels: backport version-15-hotfix

#3302 fix: use item gst details in GSTR-1 report and minor refactor
  india_compliance/gst_india/report/gstr_1/gstr_1.py
Labels: squash, p1

#3222 fix: Update Implementation for HSN_B2B and HSN_B2C Bifurcation
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/report/gstr_1/gstr_1.js
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.js
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/test_hsn_wise_summary_of_outward_supplies.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
  india_compliance/patches/v15/set_default_hsn_bifurcation_date.py
Labels: squash, backport version-14-hotfix, backport version-15-hotfix
