Repository resilient-tech/india-compliance, pull requests merged in 2025-02, with the labels that each got.

#3012 fix: convert ewaybill number to string for IRN retrieval; hence support its indexing
  india_compliance/gst_india/print_format/e_waybill/e_waybill.html
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.html
Labels: backport version-14-hotfix, backport version-15-hotfix

#3016 fix: new versions for black, isort, flake8
  .pre-commit-config.yaml
  india_compliance/gst_india/overrides/payment_entry.py
  india_compliance/gst_india/overrides/purchase_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3009 fix: Suggest Invoices that Should be Marked as Pending
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.js
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.json
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/utils/gstin_info.py
Labels: p1

#3011 feat: GSTIN Status report
  india_compliance/gst_india/report/gstin_status/__init__.py
  india_compliance/gst_india/report/gstin_status/gstin_status.js
  india_compliance/gst_india/report/gstin_status/gstin_status.json
  india_compliance/gst_india/report/gstin_status/gstin_status.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
Labels: squash, backport version-15-hotfix

#2766 fix: add filing period selection in gstr-1 beta
  india_compliance/gst_india/api_classes/taxpayer_base.py
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.js
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/patches/v15/update_return_logs_with_filing_preference.py
  india_compliance/public/js/utils.js
Labels: squash, p1, backport version-15-hotfix

#3039 fix: GSTIN Status Report bug fixes
  india_compliance/gst_india/report/gstin_status/gstin_status.py
Labels: backport version-15-hotfix

#3043 fix: check if GSTIN info can be fetched
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.json
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.py
  india_compliance/gst_india/doctype/gst_invoice_management_system/test_gst_invoice_management_system.py
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-15-hotfix

#3036 feat: extensive support for GSTR1 quarterly filing
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.js
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/utils/__init__.py
  india_compliance/gst_india/utils/gstin_info.py
  india_compliance/gst_india/utils/gstr_1/__init__.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/patches/v15/update_return_logs_with_filing_preference.py
Labels: squash, backport version-15-hotfix

#3054 fix: no need to use ipify API
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/taxpayer_base.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3057 fix: more descriptive label
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
Labels: backport version-15-hotfix

#3062 fix: Remove Redundant Function
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
Labels: backport version-15-hotfix

#3064 fix: show `Filing Preference` once during view GSTR-1
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
Labels: backport version-15-hotfix

#3060 fix: update filing preference for the first time if log is unavailable
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
Labels: backport version-15-hotfix

#3068 fix: check if a NIL return can be filed
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
Labels: backport version-15-hotfix

#3067 fix: Create `GST Return Log` only when filing preference is available
  india_compliance/gst_india/utils/gstin_info.py
Labels: backport version-15-hotfix

#3046 feat: India Compliance API Usage Report
  india_compliance/gst_india/report/india_compliance_api_usage/__init__.py
  india_compliance/gst_india/report/india_compliance_api_usage/india_compliance_api_usage.js
  india_compliance/gst_india/report/india_compliance_api_usage/india_compliance_api_usage.json
  india_compliance/gst_india/report/india_compliance_api_usage/india_compliance_api_usage.py
  india_compliance/gst_india/workspace/gst_india/gst_india.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#3073 fix: specify "India Compliance API Usage" as query report in workspace
  india_compliance/gst_india/workspace/gst_india/gst_india.json
Labels: backport version-15-hotfix

#3049 fix: refresh GSTIN status only when creating transactions
  india_compliance/gst_india/client_scripts/party.js
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gst_settings/gst_settings.py
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/patches.txt
  india_compliance/patches/v14/update_gstin_status_refresh_interval.py
  india_compliance/public/js/transaction.js
  india_compliance/public/js/utils.js
Labels: backport version-15-hotfix

#3075 fix: add Amendments data in reconcile tab
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
Labels: backport version-15-hotfix

#3076 fix: Handle Invoice Ignore/Unignore based on IMS Action
  india_compliance/gst_india/data/test_ims.json
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.py
  india_compliance/gst_india/doctype/gst_invoice_management_system/test_gst_invoice_management_system.py
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.json
  india_compliance/gst_india/doctype/gst_inward_supply/gst_inward_supply.py
  india_compliance/gst_india/utils/gstr_2/test_ims.py
  india_compliance/patches/v15/update_action_for_rejected_invoices_in_gst_inward_supply.py
Labels: p1, backport version-15-hotfix

#2273 fix: JSON Mapping for ITC-04 filing
  india_compliance/gst_india/overrides/test_subcontracting_transaction.py
  india_compliance/gst_india/report/gst_job_work_stock_movement/gst_job_work_stock_movement.js
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_1/test_gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_mapper_utils.py
  india_compliance/gst_india/utils/itc_04/__init__.py
  india_compliance/gst_india/utils/itc_04/itc_04_data.py
  india_compliance/gst_india/utils/itc_04/itc_04_export.py
  india_compliance/gst_india/utils/itc_04/itc_04_json_map.py
  india_compliance/gst_india/utils/itc_04/test_itc_04_export.py
  india_compliance/gst_india/utils/itc_04/test_itc_04_json_map.py
Labels: squash, backport version-15-hotfix

#2801 fix: APIs for regeneration of GSTR-2B
  india_compliance/gst_india/api_classes/taxpayer_returns.py
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.js
  india_compliance/gst_india/doctype/gstr_import_log/gstr_import_log.json
  india_compliance/gst_india/doctype/gstr_import_log/gstr_import_log.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/public/js/gstr_2b.js
  india_compliance/public/js/purchase_reconciliation_tool.bundle.js
  india_compliance/public/js/utils.js
Labels: p1, backport version-15-hotfix

#3080 refactor: update code for better radability and bug fixes
  india_compliance/gst_india/report/gstin_status/gstin_status.js
Labels: backport version-15-hotfix

#3041 Fix: Handle multi-currency scenarios in advance payment entries.
  india_compliance/gst_india/overrides/sales_invoice.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#3005 feat: Update Address In Address Doctype using button
  india_compliance/gst_india/client_scripts/address.js
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix
