Repository resilient-tech/india-compliance, pull requests merged in 2025-10, with the labels that each got.

#3711 fix: use load_doc for onload trigger in get_source_destination_address function
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_waybill.py
Labels: p1, backport version-15-hotfix

#3710 fix: do not include `place of supply` in CDNUR if it is export document
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py
  india_compliance/gst_india/report/gstr_1/gstr_1.py
  india_compliance/gst_india/utils/exporter.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_mapper_utils.py
Labels: p1, backport version-14-hotfix

#3709 fix: do not include `place of supply` in CDNUR if it is export document
  india_compliance/gst_india/doctype/gstr_1/gstr_1_export.py
  india_compliance/gst_india/utils/exporter.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/gst_india/utils/gstr_mapper_utils.py
Labels: p1
