Repository resilient-tech/india-compliance, pull requests merged in 2025-08, with the labels that each got.

#3607 fix: update valid HSN length for e-Invoice and e-Waybill validation
  india_compliance/gst_india/overrides/sales_invoice.py
  india_compliance/gst_india/utils/transaction_data.py
Labels: p1, backport version-14-hotfix, backport version-15-hotfix

#3594 fix: add option to exclude ISD in get_gstin_list function
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.js
  india_compliance/gst_india/doctype/gst_invoice_management_system/gst_invoice_management_system.js
  india_compliance/gst_india/doctype/gstr_1/gstr_1.js
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/utils/__init__.py
  india_compliance/public/js/components/set_gstin_options.js
  india_compliance/public/js/utils.js
Labels: p1

#3620 fix: ensure error is raised if IRN is not present in the response
  india_compliance/gst_india/api_classes/nic/e_invoice.py
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/test_e_invoice.py
Labels: backport version-15-hotfix

#3555 refactor: enhance mask_sensitive_info in BaseAPI
  india_compliance/gst_india/api_classes/base.py
  india_compliance/gst_india/api_classes/nic/e_invoice.py
  india_compliance/gst_india/api_classes/nic/e_waybill.py
  india_compliance/gst_india/api_classes/taxpayer_base.py
  india_compliance/gst_india/api_classes/test_mask_sensitive_info.py
Labels: squash

#3590 chore: resolve semgrep errors
  india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/income_tax_india/overrides/company.py
  india_compliance/patches/post_install/add_einvoice_status_field.py
  india_compliance/patches/post_install/update_reverse_charge_and_export_type.py
Labels: squash
