Repository resilient-tech/india-compliance, pull requests merged in 2025-01, with the labels that each got.

#2915 fix: IRN generated in another portal error
  india_compliance/gst_india/api_classes/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2913 fix: handle multiple GSTR-1 beta requests
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2897 fix(gstr-1): handle gov api error when downloading and make it optional for unfiled returns
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gst_settings/gst_settings.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/setup/__init__.py
  india_compliance/patches.txt
  india_compliance/patches/v14/rename_gstr1_settings.py
  india_compliance/patches/v14/update_default_gstr1_settings.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2930 fix: set reconciliation status for unlinked document in purchase reco tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2903 fix: unique name for events and doctype parameter alone is redundant
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/gst_india/utils/gstr_2/__init__.py
  india_compliance/gst_india/utils/gstr_2/gstr.py
Labels: squash, p1, backport version-14-hotfix, backport version-15-hotfix

#2946 ci: correct mariadb-client version
  .github/helper/install.sh
Labels: backport version-14-hotfix, backport version-15-hotfix

#2949 fix: suggest default return period correct when in first period
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2938 fix: selectively download sections in GSTR-1 based on summary information
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2945 fix: save nil filing information in gst return log
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
  india_compliance/public/js/components/data_table_manager.js
Labels: backport version-14-hotfix, backport version-15-hotfix

#2906 feat: allow filing of Nil return for GSTR-1
  india_compliance/gst_india/api_classes/taxpayer_returns.py
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.json
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/utils/gstr_1/gstr_1_download.py
Labels: squash, p1, backport version-15-hotfix

#2960 fix: multiple fixes related to GSTR-1 tool
  india_compliance/gst_india/doctype/gst_return_log/generate_gstr_1.py
  india_compliance/gst_india/doctype/gst_return_log/gst_return_log.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.js
  india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py
  india_compliance/public/js/gst_api_handler.js
Labels: backport version-15-hotfix

#2967 fix: `ignore_permissions` when handeling missing gstr2a 2b transactions
  india_compliance/gst_india/utils/gstr_2/gstr_2a.py
  india_compliance/gst_india/utils/gstr_2/gstr_2b.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2973 fix: enqueue only once for transactions created in bulk
  india_compliance/gst_india/doctype/gstin/gstin.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2953 fix: Improved Data Flow in Purchase Reconciliation Tool
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_detail_comparison.html
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.js
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.json
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/public/js/gst_api_handler.js
Labels: squash, p1, backport version-15-hotfix

#2986 feat #2965: add E-Waybill Detailed print format
  india_compliance/gst_india/print_format/e_waybill_detailed/__init__.py
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.css
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.html
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.json
  india_compliance/gst_india/utils/jinja.py
  india_compliance/hooks.py
Labels: backport version-14-hotfix, backport version-15-hotfix

#2991 fix: update UI of e-Waybill print-format
  india_compliance/gst_india/print_format/e_waybill/e_waybill.css
  india_compliance/gst_india/print_format/e_waybill/e_waybill.html
  india_compliance/gst_india/print_format/e_waybill_detailed/e_waybill_detailed.css
Labels: backport version-14-hotfix, backport version-15-hotfix

#2982 fix: retain user Selected Year after save in GSTR-3B Report
  india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.js
  india_compliance/public/js/components/set_gstin_options.js
  india_compliance/public/js/gstr1.bundle.js
  india_compliance/public/js/india_compliance.bundle.js
  india_compliance/public/js/purchase_reconciliation_tool.bundle.js
Labels: squash, backport version-15-hotfix
