Repository resilient-tech/india-compliance, pull requests merged in 2025-09, with the labels that each got.

#3634 fix: use sbool for boolean conversions for frappe.whitelist
  india_compliance/gst_india/doctype/gstin/gstin.py
  india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py
  india_compliance/gst_india/overrides/transaction.py
  india_compliance/gst_india/utils/e_invoice.py
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/gstin_info.py
Labels: p1

#3635 fix: remove unnecessary string checks for boolean parameters in get_gstr_1_json function
  india_compliance/gst_india/doctype/gstr_1/gstr_1_export.py
Labels: p1, backport version-15-hotfix

#3654 fix: add default invoice sub categories based on selected sub section in Purchase Register Beta
  india_compliance/gst_india/report/gst_purchase_register/gst_purchase_register.py
Labels: backport version-15-hotfix

#3662 fix: use string instead of object for description
  india_compliance/public/js/utils.js
Labels: do not backport

#3673 perf: optimize tax updates for items with HSN code using bulk operations
  india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py
Labels: p1

#3692 refactor: replace IfNull with isnull for better null handling in queries
  india_compliance/gst_india/doctype/gst_invoice_management_system/__init__.py
  india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py
  india_compliance/gst_india/report/gstin_status/gstin_status.py
Labels: backport version-15-hotfix

#3688 fix: do not generate e-waybill using IRN if invoice has non-taxable items
  india_compliance/gst_india/data/test_e_invoice.json
  india_compliance/gst_india/data/test_e_waybill.json
  india_compliance/gst_india/utils/e_waybill.py
  india_compliance/gst_india/utils/test_e_invoice.py
  india_compliance/gst_india/utils/test_e_waybill.py
  india_compliance/tests/test_records.json
Labels: backport version-14-hotfix, backport version-15-hotfix

#3698 fix: allow sub supply type as export for Sales Invoice in e-Waybill generation
  india_compliance/gst_india/client_scripts/e_waybill_actions.js
Labels: backport version-15-hotfix
